# Generated by Django 5.1.6 on 2025-08-14 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0005_meep_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='shared_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='musker.meep'),
        ),
    ]
